services:
  trainer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: model-trainer
    env_file:
      - .env            # Load variables from .env
    volumes:
      - ./mlruns:/app/mlruns

