services:
  trainer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: model-trainer
    environment:
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
    volumes:
      - ./mlruns:/app/mlruns

